INSERT INTO TB_OPERATOR (OPERATOR_EMAIL, OPERATOR_NAME, OPERATOR_PASSWORD) VALUES ('gerson@email.com', 'Gerson', '$2a$12$G.VyzhU1vH1x5CxO.sfaSuJDTrSLbJ.NIjweNaj35ww1oPZHPY3DG');
INSERT INTO TB_OPERATOR (OPERATOR_EMAIL, OPERATOR_NAME, OPERATOR_PASSWORD) VALUES ('juliana@email.com', 'Juliana', '$2a$12$G.VyzhU1vH1x5CxO.sfaSuJDTrSLbJ.NIjweNaj35ww1oPZHPY3DG');

INSERT INTO TB_ROLE (ROLE_DESCRIPTION) VALUES ('ROLE_OPERATOR');
INSERT INTO TB_ROLE (ROLE_DESCRIPTION) VALUES ('ROLE_ADMIN');

INSERT INTO TB_OPERATOR_ROLE (OPERATOR_ID, ROLE_ID) VALUES (1, 1);
INSERT INTO TB_OPERATOR_ROLE (OPERATOR_ID, ROLE_ID) VALUES (2, 1);
INSERT INTO TB_OPERATOR_ROLE (OPERATOR_ID, ROLE_ID) VALUES (2, 2);